-- Create assessments table
CREATE TABLE IF NOT EXISTS assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  show_name TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  questions JSONB NOT NULL,
  category TEXT NOT NULL,
  show_details JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Create comments table
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  show_name TEXT NOT NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Add user_id column to assessments
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL;

-- Add user_id column to comments
ALTER TABLE comments ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL;

-- Create an index on show_name for faster searches
CREATE INDEX IF NOT EXISTS idx_assessments_show_name ON assessments(show_name);
CREATE INDEX IF NOT EXISTS idx_comments_show_name ON comments(show_name);

-- Create an index on date for faster sorting
CREATE INDEX IF NOT EXISTS idx_assessments_date ON assessments(date);
CREATE INDEX IF NOT EXISTS idx_comments_date ON comments(created_at);

-- Create an index on user_id for faster user-specific queries
CREATE INDEX IF NOT EXISTS idx_assessments_user_id ON assessments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);

-- Enable Row Level Security (RLS)
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Create policies for assessments
CREATE POLICY "Users can view all assessments" ON assessments
  FOR SELECT
  USING (true);

CREATE POLICY "Users can insert their own assessments" ON assessments
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Users can update their own assessments" ON assessments
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Users can delete their own assessments" ON assessments
  FOR DELETE
  USING (true);

-- Create policies for comments
CREATE POLICY "Users can view all comments" ON comments
  FOR SELECT
  USING (true);

CREATE POLICY "Users can insert their own comments" ON comments
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Users can update their own comments" ON comments
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Users can delete their own comments" ON comments
  FOR DELETE
  USING (true); 